### ISSUE TITLE
Error Code: 299, targeted address: 0x00007FF6C55C1950

### ISSUE THREAD

**Issue by Etrud** [shaneMenzies/BaronyPA#4]
BaronyPA: An error occurred in ReadProcessMemory, Error Code: 299, targeted address: 0x00007FF6C55C1950

When running the plugin on version 1.4.287 of Mumble will spam mumble chat with the following error every second. I tried an older version of Mumble but same issue. Also, ty for what you do :)

![image](https://github.com/shaneMenzies/BaronyPA/assets/39094482/95c81562-9f26-49ee-8662-eff77e61b997)

**Comment by UMJ1127** [comment]
I wish this amazing plugin would be fixed someday...

**Comment by 0nionManLV** [comment]
Pleease 🥺🥺🥺

The update instructions are pretty unclear...search what? search where? It's not in this repo according to github search. Neither does VSC find it. Is it meant to be Barony source code?

**Comment by PropFault** [comment]
Please Fix this. Im too stupid to do it myself

**Comment by BrutalEddie** [comment]
Still broken. Very cool.

**Comment by Citrisfur** [comment]
Still an issue, although I got a different memory error of 0x0000000000000000. Played around with it myself and couldn't figure out anything different, I agree update instructions seem to make no sense.

**Comment by shaneMenzies** [comment]
These issues should be fixed now, I updated the plugin for v4.2.1 of Barony.

Because of how this plugin works it needs to be updated any time Barony gets updated, and I kinda have to agree that I didn't even leave the best instructions for updating it even for myself so I'll probably rewrite those to be more clear about that in case other people want to try updating it in the future.
